var environments = {};

environments.staging = {
  'version' : '1.0.0',
  'codeName' : 'Rinjani',
  'httpPort' : 8021,
  'httpsPort' : 8022,
  'envName' : 'staging',
  'sqliteDBFile': '',
  'pgsqlDBHost' : '',
  'pgsqlDBPort' : ,
  'pgsqlDBUser' : '',
  'pgsqlDBPass' : '',
  'pgsqlDBName' : '',
  'mysqlDBHost' : '',
  'mysqlDBPort' : ,
  'mysqlDBUser' : '',
  'mysqlDBPass' : '',
  'mysqlDBName' : '',
  'dhkpDBHost' : '',
  'dhkpDBPort' : ,
  'dhkpDBUser' : '',
  'dhkpDBPass' : '',
  'dhkpDBName' : '',
  'oracleDBUser' : '',
  'oracleDBPass' : '',
  'oracleDBPort' : ,
  'oracleDBAddr' : '',
  'oracleDBTNSN' : '',
  'fileUploadTempDir' : '',
  'fileUploadDir' : '',
  'hashingPairs' : '',
  'hashingSecret' : '',
  'dsEndPoint' : '-',
  'capilDSEndPoint' : '',
  'accessId' : [''],
  'accessKey' : [''],
  'jwtId' : [''],
  'accessSignature' : [''],
  'dukcapiluserid' : '',
  'dukcapilpasswd' : ''
};

environments.production = {
  'version' : '1.0.0',
  'codeName' : 'Rinjani',
  'httpPort' : 9021,
  'httpsPort' : 9022,
  'envName' : 'production',
  'sqliteDBFile': '',
  'pgsqlDBHost' : '',
  'pgsqlDBPort' : ,
  'pgsqlDBUser' : '',
  'pgsqlDBPass' : '',
  'pgsqlDBName' : '',
  'mysqlDBHost' : '',
  'mysqlDBPort' : ,
  'mysqlDBUser' : '',
  'mysqlDBPass' : '',
  'mysqlDBName' : '',
  'dhkpDBHost' : '',
  'dhkpDBPort' : ,
  'dhkpDBUser' : '',
  'dhkpDBPass' : '',
  'dhkpDBName' : '',
  'oracleDBUser' : '',
  'oracleDBPass' : '',
  'oracleDBPort' : ,
  'oracleDBAddr' : '',
  'oracleDBTNSN' : '',
  'hashingPairs' : '',
  'hashingSecret' : '',
  'dsEndPoint' : '-',
  'capilDSEndPoint' : '',
  'accessId' : [''],
  'accessKey' : [''],
  'jwtId' : [''],
  'accessSignature' : [''],
  'dukcapiluserid' : '',
  'dukcapilpasswd' : ''
};
var currentEnvironment = typeof(process.env.NODE_ENV) == 'string' ? process.env.NODE_ENV.toLowerCase() : '';
var environmentToExport = typeof(environments[currentEnvironment]) == 'object' ? environments[currentEnvironment] : environments.staging;
module.exports = environmentToExport;